typedef enum FragmentBufferIndex {
    FragmentBufferVertexUniforms = 0,
    FragmentBufferMaterialUniforms = 1,
    FragmentBufferLighting = 2,
    FragmentBufferShadows = 3,
    FragmentBufferShadowData = 4,
    FragmentBufferCustom0 = 5,
    FragmentBufferCustom1 = 6,
    FragmentBufferCustom2 = 7,
    FragmentBufferCustom3 = 8,
    FragmentBufferCustom4 = 9,
    FragmentBufferCustom5 = 10,
    FragmentBufferCustom6 = 11,
    FragmentBufferCustom7 = 12,
    FragmentBufferCustom8 = 13,
    FragmentBufferCustom9 = 14,
    FragmentBufferCustom10 = 15,
    FragmentBufferProjectorMatrices = 16,
    FragmentBufferProjectorTransforms = 17,
    FragmentBufferDirectShadows = 18,
    FragmentBufferDirectShadowMatrices = 19
} FragmentBufferIndex;

typedef enum FragmentTextureIndex {
    FragmentTextureCustom0 = 0,
    FragmentTextureCustom1 = 1,
    FragmentTextureCustom2 = 2,
    FragmentTextureCustom3 = 3,
    FragmentTextureCustom4 = 4,
    FragmentTextureCustom5 = 5,
    FragmentTextureCustom6 = 6,
    FragmentTextureCustom7 = 7,
    FragmentTextureCustom8 = 8,
    FragmentTextureCustom9 = 9,
    FragmentTextureCustom10 = 10,
    FragmentTextureCustom11 = 11,
    FragmentTextureCustom12 = 12,
    FragmentTextureCustom13 = 13,
    FragmentTextureCustom14 = 14,
    FragmentTextureCustom15 = 15,
    FragmentTextureCustom16 = 16,
    FragmentTextureCustom17 = 17,
    FragmentTextureCustom18 = 18,
    FragmentTextureCustom19 = 19,
    FragmentTextureCustom20 = 20,
    FragmentTextureCustom21 = 21,
    FragmentTextureCustom22 = 22,
    FragmentTextureCustom23 = 23,
    FragmentTextureCustom24 = 24,
    FragmentTextureShadow0 = 25,
    FragmentTextureShadow1 = 26,
    FragmentTextureShadow2 = 27,
    FragmentTextureShadow3 = 28,
    FragmentTextureShadow4 = 29,
    FragmentTextureShadow5 = 30,
    FragmentTextureShadow6 = 31,
    FragmentTextureShadow7 = 32,
    FragmentTextureProjector0 = 33,
    FragmentTextureDirectShadow0 = 41
} FragmentTextureIndex;

typedef enum FragmentSamplerIndex {
    FragmentSamplerCustom0 = 0,
    FragmentSamplerCustom1 = 1,
    FragmentSamplerCustom2 = 2,
    FragmentSamplerCustom3 = 3,
    FragmentSamplerCustom4 = 4,
    FragmentSamplerCustom5 = 5,
    FragmentSamplerCustom6 = 6,
    FragmentSamplerCustom7 = 7,
    FragmentSamplerCustom8 = 8,
    FragmentSamplerCustom9 = 9,
    FragmentSamplerCustom10 = 10
} FragmentSamplerIndex;
