name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: 'macos-14'
    steps:
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: '15.4'
      - name: Check out Satin
        uses: actions/checkout@v2
      - name: Build Satin
        run: |
          set -euo pipefail
          swift build
      - name: Test Satin
        run: |
          set -euo pipefail
          swift test
